version: '2'
services:
  traefik:
    image: traefik
    network_mode: host
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik/services.yml:/etc/traefik/services.yml"
  postgres:
    build: ./postgres/
    ports:
     - "5432:5432"
  mailhog:
    image: mailhog/mailhog
    ports:
    - "1025:1025"
    - "8025:8025"